In [1]:
import numpy as np #import NumPy

In [2]:
#Create 1-D array
arr_1d=np.array([1,2,3,4])
print(arr_1d)

[1 2 3 4]


In [4]:
type(arr_1d) #type of var

numpy.ndarray

In [5]:
arr_1d.ndim #dimension of array

1

In [6]:
#Create 2-D array
arr_2d=np.array([[1,2,3],[4,5,6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [7]:
arr_2d.ndim #dimension of array

2

In [8]:
arr_2d.size #number of elements

6

In [9]:
arr_2d.shape #(row,col)

(2, 3)

In [10]:
arr_1d.dtype #data type of array

dtype('int32')

In [6]:
print(np.ones((3,3)))
print(np.zeros((3,2)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [7]:
print(np.ones((3,4), dtype=int))
print(np.zeros((3,4), dtype=bool))

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[False False False False]
 [False False False False]
 [False False False False]]


In [8]:
print(np.ones((3,4), dtype=str))

[['1' '1' '1' '1']
 ['1' '1' '1' '1']
 ['1' '1' '1' '1']]
