# Array Slicing

In [2]:
import numpy as np

In [12]:
a1=np.arange(1,101).reshape(10,10)
print(a1)
print(a1.itemsize)#bytes required for each item
print(a1.size)#number of items

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]
4
100


In [8]:
a1[:,0:2]#all rows first two columns

array([[ 1,  2],
       [11, 12],
       [21, 22],
       [31, 32],
       [41, 42],
       [51, 52],
       [61, 62],
       [71, 72],
       [81, 82],
       [91, 92]])

In [9]:
a1[1:4,1:3] #1-3 row and 1-2 row

array([[12, 13],
       [22, 23],
       [32, 33]])

In [ ]:
#access whole matrix
a1[:]
a1[::]
a1[:,:]

# Array Concatination

In [14]:
a2=np.arange(1,17).reshape(4,4)
a3=np.arange(17,33).reshape(4,4)
print(a2)
print(a3)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [18]:
a4=np.concatenate((a2,a3))#by default axis=0, row wise
print(a4)
a5=np.vstack((a2,a3))
print(a5)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [21]:
a6=np.concatenate((a2,a3),axis=1)#axis=1, col wise
print(a6)
a7=np.hstack((a2,a3))
print(a7)

[[ 1  2  3  4 17 18 19 20]
 [ 5  6  7  8 21 22 23 24]
 [ 9 10 11 12 25 26 27 28]
 [13 14 15 16 29 30 31 32]]
[[ 1  2  3  4 17 18 19 20]
 [ 5  6  7  8 21 22 23 24]
 [ 9 10 11 12 25 26 27 28]
 [13 14 15 16 29 30 31 32]]


# Array Split

In [28]:
list1=np.split(a2,2) #axis by default 0, row wise,returns a list
list2=np.split(a2,2,axis=1)#axis=1, col wise
print(list1)
print(list2)
print(list1[0])
print(list2[1])

[array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])]
[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16]])]
[[1 2 3 4]
 [5 6 7 8]]
[[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]]


In [31]:
a8=np.array([2,4,3,4,0,4,7])
list3=np.split(a8,[2,5,6])#list of index(exclusive) as second para
print(list3)
#try with 2d array

[array([2, 4]), array([3, 4, 0]), array([4]), array([7])]
