# Built-in Functions

In [ ]:
import numpy as np

In [2]:
#np.arange(start,end,step)
a1=np.arange(2,13)
a2=np.arange(1,20,2)
print(a1)
print(a2)

[ 2  3  4  5  6  7  8  9 10 11 12]
[ 1  3  5  7  9 11 13 15 17 19]


In [5]:
#np.linspace(start,end,num_of_val)
a3=np.linspace(1,8,4)
a4=np.linspace(2,6)
print(a3)
print(a4)
print(len(a4))

[1.         3.33333333 5.66666667 8.        ]
[2.         2.08163265 2.16326531 2.24489796 2.32653061 2.40816327
 2.48979592 2.57142857 2.65306122 2.73469388 2.81632653 2.89795918
 2.97959184 3.06122449 3.14285714 3.2244898  3.30612245 3.3877551
 3.46938776 3.55102041 3.63265306 3.71428571 3.79591837 3.87755102
 3.95918367 4.04081633 4.12244898 4.20408163 4.28571429 4.36734694
 4.44897959 4.53061224 4.6122449  4.69387755 4.7755102  4.85714286
 4.93877551 5.02040816 5.10204082 5.18367347 5.26530612 5.34693878
 5.42857143 5.51020408 5.59183673 5.67346939 5.75510204 5.83673469
 5.91836735 6.        ]
50


In [17]:
a5=np.array([1,2,3,4,5,6,7,8])
a6=a5.reshape(2,4)
a7=a5.reshape(4,2)
a8=a5.reshape(2,2,2)
print(a6)
print(a7)
print("a8: \n"+str(a8))

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
a8: 
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [27]:
a13=np.arange(0,12).reshape(2,6)

#RAVEL()
(i) Return only reference/view of original array
(ii) If you modify the array you would notice that the value of original array also changes.
(iii) Ravel is faster than flatten() as it does not occupy any memory.

In [19]:
a8.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8])

#FLATTEN()
(i) Return copy of original array
(ii) If you modify any value of this array value of original array is not affected.
(iii) Flatten() is comparatively slower than ravel() as it occupies memory.

In [25]:
a9=a8.flatten()
a10=a8.flatten('F')
a11=a8.flatten('A')
a12=a8.flatten('K')
print(a9)
print(a10)
print(a11)
print(a12)

[1 2 3 4 5 6 7 8]
[1 5 3 7 2 6 4 8]
[1 2 3 4 5 6 7 8]
[1 2 3 4 5 6 7 8]


In [29]:
a14=a13.transpose()
a15=a13.T
print(a14)
print(a15)

[[ 0  6]
 [ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]]
[[ 0  6]
 [ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]]
