# Mathematical functions

In [1]:
import numpy as np

In [4]:
a1=np.arange(1,10).reshape(3,3)
a2=np.arange(1,10).reshape(3,3)
print(a1)
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
a3=a1+a2
a4=np.add(a1,a2)
print(a3)
print(a4)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [8]:
a5=np.subtract(a1,a2)#a1-a2
a6=np.divide(a1,a2)#a1/a2
a7=np.multiply(a1,a2)#a1*a2
a8=a1.dot(a2)#a1@a2

In [13]:
v1=a1.max()#max value
print(v1)
v2=a1.argmax()#index of max value
print(v2)
v3=a1.min()#min value
print(v3)
v4=a1.argmin()#index of min value
print(v4)

9
8
1
0


In [15]:
a9=a1.max(axis=0)#column wise max value
print(a9)
a10=a1.max(axis=1)#row wise max value
print(a10)
a11=a1.min(axis=0)#column wise min value
print(a11)
a12=a1.max(axis=1)#row wise min value
print(a12)

[7 8 9]
[3 6 9]
[1 2 3]
[3 6 9]


In [17]:
v3=np.sum(a1)#sum of whole array
print(v3)
a13=np.sum(a1,axis=0)#sum of each column
print(a13)
a14=np.sum(a1,axis=1)#sum of each row
print(a14)

45
[12 15 18]
[ 6 15 24]


In [26]:
v4=np.mean(a1) #mean
print(v4)
a15=np.sqrt(a1)#square root
print(a15)
v5=np.std(a1)#standard deviation
print(v5)
a16=np.exp(a1)#exponential
print(a16)
a17=np.log(a1)#log
print(a17)
a18=np.log10(a1)#log base 10
print(a18)

5.0
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]
2.581988897471611
[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]
[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]
 [1.94591015 2.07944154 2.19722458]]
[[0.         0.30103    0.47712125]
 [0.60205999 0.69897    0.77815125]
 [0.84509804 0.90308999 0.95424251]]


In [28]:
base = 42 #n base log
a19 = np.log(a1) / np.log(base)
print(a19)

[[0.         0.18544902 0.29392975]
 [0.37089805 0.4305993  0.47937877]
 [0.52062123 0.55634707 0.5878595 ]]
