# Numpy with random
https://numpy.org/doc/1.16/reference/routines.random.html

In [ ]:
import random
import numpy as np

In [12]:
np.random.random((3,3))

array([[0.03730248, 0.41218521, 0.59393626],
       [0.71423301, 0.40497881, 0.1247829 ],
       [0.69498143, 0.40422784, 0.73035812]])

In [22]:
np.random.randint(1,4)
np.random.randint(1,9,(3,3))
np.random.randint(1,9,(4,3,3))

array([[[5, 4, 7],
        [6, 7, 5],
        [3, 7, 5]],

       [[8, 5, 8],
        [4, 6, 3],
        [8, 5, 3]],

       [[8, 2, 6],
        [8, 6, 1],
        [2, 2, 8]],

       [[6, 4, 7],
        [7, 3, 5],
        [2, 4, 4]]])

In [23]:
np.random.seed(20) #(2^32)-1 values
np.random.randint(1,9,(3,3))

array([[4, 3, 8],
       [8, 5, 3],
       [2, 5, 4]])

In [26]:
np.random.rand(3)
np.random.rand(2,3)
np.random.randn(2,3)

array([[-2.09877391, -1.85559768,  0.55097131],
       [-0.36372358, -0.99642606, -1.1653022 ]])

In [29]:
a1=[9,5,8,4,5,75,6,6,7,5,4,29,4,3,94,8,7,5,8,4]
np.random.choice(a1)

29

In [31]:
np.random.permutation(a1)#shuffle

array([ 6, 29,  3,  5,  9,  4,  6,  4,  5,  4,  7,  5,  8, 75,  5,  7,  4,
       94,  8,  8])